version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install
      timeout: 120
      runas: root
    - location: scripts/start
      timeout: 60
      runas: root